spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://awseb-e-cmb83k93ag-stack-awsebrdsdatabase-jsnetrppetyc.clo44oag455u.ap-northeast-2.rds.amazonaws.com:3306/nolook?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gihong0409
    password: rlghd134!
jwt:
  secret: rxgPJNULH8XHYyTSa5/95KMwj7k66LW0ImkVKerGGCQ= #your_secret_key
  expiration: 86400000 # 1 day in milliseconds

server:
  port: 8080 # AWS에서 기본 포트로 5000이 지정돼있기 때문에 http:8080이지만 임의로 5000으로 지정함
